### ISSUE TITLE
API calls for reasoning tasks

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#10]
A first implementation of the theory GUI (vocabulary, facts) is now done. Theories can be created, deleted and updated (no copying etc., so far).
In my theory GUI draft, I included buttons for checking the consistency of the axiomatization (= set of formalized facts, nothing query specific) as well as checking logical independence. While neither task is crucial, I was thinking about how to implement reasoning API queries in general. Will you provide, for every specific reasoning task, a dedicated API method (e.g. `api/theories/id/consistency`, `api/queries/id/run` etc.), or do I need to create the reasoning tasks in the front end (and we have a general purpose `api/run` method)? I think the first option is more suited as otherwise users could create arbitrary reasoning tasks and send them to the back end. 

What do you think?

Also, is consistency checking possible with MleanCoP? It can only find inconsistencies and not show consistency, right?

**Comment by shaolintl** [comment]
I agree with you with regard to the tasks distribution. We should add all the different API calls. Regarding MleanCoP, I might have seen some model generated once or maybe I am mistaken. Anyway, we can aim in showing inconsistency by proving the implication of a falsity. Regarding independence, is there a smart way of proving it except trying to prove each formula from all others? If not, then this method would be very slow and wont fit an asynchronous approach. But, we can run it in the background and instead of responding to the user, just change a field in the theory in the DB. What do you think? I will do the inconsistency check for now.

**Comment by shaolintl** [comment]
I added in 955bcda the API for checking a theory consistency. I am using the async approach here so every call will have an approximate delay of 1 second

**Comment by shaolintl** [comment]
I noticed I have never answered @lex-lex question about proving consistency. Yes, the prover can only prove inconsistency but it does report that inconsistency is not a theorem on most cases, which I take as consistency. It is true that in some cases it will be timeouted before a reply can be returned. Do you see a problem with this approach?

**Comment by lex-lex** [comment]
Not a problem per se, would be nice though to use a model finder to explicitly show consistency in the future. But this can be discussed again later.

**Comment by shaolintl** [comment]
It’s a problem since not being able to prove doesn’t always terminate. For
now I’ll send back a message that not being able to prove means normally
that’s counter satisfiable.
